Repository caarlos0/env, pull requests merged in 2021-08, with the labels that each got.

#187 feat: Add option: 'required' by default
  env.go
  env_test.go
Labels: size/S

#188 docs: Fix spelling in readme
  README.md
Labels: size/XS

#185 feat: onset hook
  README.md
  env.go
  env_test.go
Labels: size/L
