Repository caarlos0/env, pull requests merged in 2023-04, with the labels that each got.

#256 feat!: remove ParseWithFuncs, add ParseWithOptions
  README.md
  env.go
  env_test.go
  go.mod
Labels: enhancement, size/L

#259 build: test on go stable and oldstable
  .github/workflows/build.yml
Labels: enhancement, size/XS

#264 Update and fix examples in readme for v8.0.0
  README.md
Labels: size/M
