Repository caarlos0/env, pull requests merged in 2024-10, with the labels that each got.

#336 implement interface { Unwrap() []error } for AggregateError
  error.go
Labels: size/XS

#330 docs: add installation instructions to README.md
  README.md
Labels: size/XS

#327 Added EditorConfig
  .editorconfig
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .golangci.yml
  README.md
  env.go
  env_test.go
  env_tomap_windows_test.go
  error.go
  go.mod
Labels: size/L

#332 Support custom tag name for envPrefix
  env.go
  env_test.go
Labels: enhancement, size/M

#340 Fix issue parsing into ptr fields with value
  env.go
  env_test.go
Labels: size/M
