Repository caarlos0/env, pull requests merged in 2024-08, with the labels that each got.

#321 fix: do not init empty arrays
  env.go
  env_test.go
  go.mod
Labels: bug, size/M

#322 docs: cleanup readme
  README.md
  env.go
  example_test.go
Labels: size/XL

#326 Added support `time.Location`
  README.md
  env.go
  env_test.go
Labels: size/M

#329 fix: improve errors
  env.go
  env_test.go
  error.go
  example_test.go
Labels: enhancement, size/M

#324 Support other names for envDefault
  env.go
  env_test.go
Labels: enhancement, size/M
